"""
Django settings for vocab project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# Basisverzeichnis des Projekts
BASE_DIR = Path(__file__).resolve().parent.parent

# settings.py
LOGIN_URL = 'login'  # Name deiner Login-URL
LOGIN_REDIRECT_URL = 'home'  # Nach Login wohin leiten


# Sicherheit
SECRET_KEY = 'django-insecure-0(6^k1pzz2nk8d)1hwjnt1jq070n+@y1&2c$0486w26v&+(#2j'
DEBUG = True
ALLOWED_HOSTS = []
# Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'channels',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vocab_project.urls'


# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",  # globale Templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vocab_project.wsgi.application'

ASGI_APPLICATION = 'chat_project.asgi.application'

# Datenbank
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vocab_app',
        'USER': 'vocab_admin',
        'PASSWORD': 'erayS123',
        'HOST': 'localhost',           # oder Server-IP, wenn remote
        'PORT': '5432',
    }
}


# Passwortvalidierung
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Sprache & Zeitzone
LANGUAGE_CODE = 'de-de'
TIME_ZONE = 'Europe/Berlin'
USE_I18N = True
USE_TZ = True

# --- STATIC FILES (CSS, JS, IMAGES) ---
STATIC_URL = '/static/'

# Hier sucht Django nach deinen CSS-Dateien während der Entwicklung
STATICFILES_DIRS = [
    BASE_DIR / "static",  # z. B. static/vocab/style.css
]

# Wenn du später "collectstatic" nutzt (für Deployment)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default Primary Key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
