# Generated by Django 5.2.7 on 2025-10-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_vocab_options_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.group'),
        ),
    ]
