# Generated by Django 5.2.7 on 2025-10-12 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_vocab_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabs', to='base.group'),
        ),
    ]
