# Generated by Django 5.2.7 on 2025-10-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_vocab_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='source_language',
            field=models.TextField(default='deutsch', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='target_language',
            field=models.TextField(default='englisch', max_length=50),
        ),
    ]
