# Generated by Django 5.2.7 on 2025-10-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_group_source_language_group_target_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='source_language',
            field=models.TextField(default='Deutsch', max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='target_language',
            field=models.TextField(default='Englisch', max_length=50),
        ),
    ]
